name: "Commit and Push"
description: "Automatically commits and pushes changes to the repository."

inputs:
  author_name:
    description: "The name of the commit author. Defaults to `qubership-actions[bot]`."
    required: false
    default: "qubership-actions[bot]"
  author_email:
    description: "The email of the commit author. Defaults to `qubership-actions[bot]@qubership.com`."
    required: false
    default: "qubership-actions[bot]@qubership.com"
  commit_message:
    description: "[ci skip] The commit message. Defaults to `Automated commit`."
    required: false
    default: "Automated commit"
  branch_name:
    description: "The branch to push to. Defaults to current branch."
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure git
      shell: bash
      run: |
        set -x
        git config --global user.email "${{ inputs.author_email }}"
        git config --global user.name "${{ inputs.author_name }}"

    - name: Commit changes
      shell: bash
      run: |
        set -x
        git add .
        git commit -m "doc: [ci skip] ${{ inputs.commit_message }}" || echo "[ci skip] No changes to commit. "
      continue-on-error: true

    - name: Push changes
      shell: bash
      run: |
        set -x
        if [ -n "${{ inputs.branch_name }}" ]; then
          git push origin HEAD:${{ inputs.branch_name }}
        else
          git push origin HEAD
        fi

branding:
  icon: "git-commit"
  color: "green"