name: Parallel Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string
      scope:
        description: 'NPM scope for the package'
        required: false
        type: string
        default: '@amdyroode'
      dist-tag:
        description: 'NPM distribution tag'
        required: false
        type: string
        default: 'latest'
      maven-release:
        description: 'Run Maven release'
        required: false
        type: boolean
        default: true
      npm-publish:
        description: 'Run NPM publish'
        required: false
        type: boolean
        default: true
      version-type:
        description: 'Maven version type'
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'
        required: false
        default: 'patch'
      maven-profile:
        description: 'Maven profile to use'
        type: choice
        options:
          - 'github'
          - 'central'
        required: false
        default: 'central'

permissions:
  contents: write
  packages: write

jobs:
  maven-release:
    if: ${{ inputs.maven-release && inputs.maven-release != 'false' }}
    uses: ./.github/workflows/maven-release-v2.yaml
    with:
      version-type: ${{ inputs.version-type }}
      profile: ${{ inputs.maven-profile }}

  npm-publish:
    if: ${{ inputs.npm-publish && inputs.npm-publish != 'false' }}
    uses: ./.github/workflows/npm-publish.yml
    with:
      version: ${{ inputs.version }}
      scope: ${{ inputs.scope }}
      dist-tag: ${{ inputs.dist-tag }}
      branch_name: main
    secrets: inherit 